name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Get version from version.php
      id: get_version
      run: |
        VERSION=$(grep "plugin->release" version.php | sed -n "s/.*'\([^']*\)'.*/\1/p")
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Version detected: $VERSION"
        
    - name: Create ZIP package
      run: |
        # Create a clean directory for the package
        mkdir -p learning_style_package
        
        # Copy all files except .git, .github, and other development files
        rsync -av --exclude='.git' --exclude='.github' --exclude='*.md' \
               --exclude='test_*' --exclude='*.log' \
               ./ learning_style_package/
        
        # Create the ZIP file
        cd learning_style_package
        zip -r ../learning_style_v${{ steps.get_version.outputs.version }}.zip .
        cd ..
        
        # Verify ZIP contents
        echo "ZIP file contents:"
        unzip -l learning_style_v${{ steps.get_version.outputs.version }}.zip
        
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Learning Style Block v${{ steps.get_version.outputs.version }}
        body: |
          ## Learning Style Block v${{ steps.get_version.outputs.version }}
          
          ### 📊 **Bloque de Estilos de Aprendizaje para Moodle**
          
          Este bloque permite evaluar y visualizar los estilos de aprendizaje de los estudiantes basado en el modelo de Felder y Silverman.
          
          ### ✨ **Características Principales**
          - **Test de Estilos de Aprendizaje** con 44 preguntas
          - **Dashboard Interactivo** con visualizaciones gráficas
          - **Exportación CSV** de resultados para profesores
          - **Gestión de Participación** por parte de administradores
          - **Responsive Design** adaptado a dispositivos móviles
          
          ### 📋 **Dimensiones Evaluadas**
          - **Activo/Reflexivo** - Procesamiento de información
          - **Sensorial/Intuitivo** - Percepción de información  
          - **Visual/Verbal** - Modalidad de entrada de información
          - **Secuencial/Global** - Comprensión de información
          
          ### 🔧 **Instalación**
          1. Descargar el archivo ZIP adjunto
          2. Extraer en `/blocks/learning_style/` en tu instalación de Moodle
          3. Visitar la página de administración para completar la instalación
          4. Agregar el bloque a los cursos deseados
          
          ### 📈 **Funcionalidades para Profesores**
          - Visualización de resultados consolidados del curso
          - Descarga de datos en formato CSV
          - Dashboard con gráficos interactivos
          - Análisis estadístico de tendencias
          
          ### 🛡️ **Seguridad y Permisos**
          - Control de acceso basado en capacidades de Moodle
          - Verificación de sesión para todas las acciones
          - Protección de datos estudiantiles
          
          ---
          
          **Versión:** ${{ steps.get_version.outputs.version }}  
          **Compatibilidad:** Moodle 2.5+  
          **Desarrollado por:** SAVIO UTB  
          **Licencia:** GPL v3  
          
        draft: false
        prerelease: false
        
    - name: Upload ZIP Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./learning_style_v${{ steps.get_version.outputs.version }}.zip
        asset_name: learning_style_v${{ steps.get_version.outputs.version }}.zip
        asset_content_type: application/zip
